name: Pre-commit Check

on:
  pull_request:
    branches: 
      - '**'
      - main
      - develop
  push:
    branches:
      - '**'
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Install Chrome
      run: |
        cd /tmp
        wget -P https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        rm -f ./google-chrome-stable_current_amd64.deb
        
    - name: Build browser bundle
      run: npm run build
        
    - name: Run tests
      run: npm test
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome