name: Publish Package

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Install Chrome For Puppeteer
      run: |
        cd /tmp
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        rm -f ./google-chrome-stable_current_amd64.deb
        
    - name: Build browser bundle
      run: npm run build
        
    - name: Run tests
      run: npm test
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
      
    - name: Update version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        npm version $NEW_VERSION --no-git-tag-version
        
    - name: Generate documentation
      run: npm run docs
        
    - name: Build for publication
      run: npm run build
        
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        message: 'chore: bump version and update docs [skip ci]'
        branch: main
        author_name: github-actions[bot]
        author_email: github-actions[bot]@users.noreply.github.com