# sync-version.yml
name: Sync Version To Develop

on:
  workflow_run:
    workflows: ["Publish Package"]
    types:
      - completed
    branches: [main]

jobs:
  sync-version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - name: Check version change
      id: check_version
      run: |
        # Get the current version from main
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        
        # Get the previous version from git history
        git checkout HEAD^1
        PREVIOUS_VERSION=$(node -p "require('./package.json').version")
        
        # Go back to current commit
        git checkout -
        
        # Compare versions
        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          echo "version_changed=true" >> $GITHUB_OUTPUT
          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        else
          echo "Version unchanged"
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Update develop version
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        git checkout develop
        npm version ${{ steps.check_version.outputs.new_version }} --no-git-tag-version --allow-same-version
    
    - name: Push to develop
      if: steps.check_version.outputs.version_changed == 'true'
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        message: 'chore: sync version with main (${{ steps.check_version.outputs.new_version }}) [skip ci]'
        branch: develop
        author_name: github-actions[bot]
        author_email: github-actions[bot]@users.noreply.github.com